# Generated by Django 3.0.5 on 2024-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='product_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
